### ISSUE TITLE
fix(title properties)

### ISSUE THREAD

**Issue by gaelHugotLm** [adeo/mozaic-design-system#502]
# 🐞 Styleguide bug report

### Description

We have some duplicate/crushed properties on title styles as below : 

` font-family: LeroyMerlin,sans-serif;` can be set by default ?
` font-weight` property can be optimized ? (without squashing)
`color` by default necessary ? (crushed by other className)

```scss
.mt-heading--semi-bold, .mt-heading--underline {
    font-family: LeroyMerlin,sans-serif;
    font-weight: 600;
}

.mt-heading--lightest {
    color: #fff;
}
.mt-heading--s {
    font-family: LeroyMerlin,sans-serif;
    font-weight: 400;
    font-size: 1.4375rem;
    line-height: 1.3913;
}
.mt-heading--center {
    text-align: center;
}
.mt-heading {
    color: #000;
    display: block;
}
```

## 🔬 Steps to reproduce the issue

Check "cours en magasin" title on this link : 
https://www-leroymerlin.kobi-gluer-frlm-web-team-nav-mag-qa.apps.op.acp.adeo.com/magasins/lesquin/

## 📷 Screenshot (optional - it might be a gif)

![image](https://user-images.githubusercontent.com/3939846/77083284-8e1b0800-69fd-11ea-9ec9-511bdffa7200.png)
