### ISSUE TITLE
fix(button properties)

### ISSUE THREAD

**Issue by gaelHugotLm** [adeo/mozaic-design-system#503]
# 🐞 Styleguide bug report

### Description

On button properties, we can optimize border property : 

As below, we can just change `border-color` property, and not use border shortcut.

prefer : 
```css
.mc-button--bordered {
    color: #78be20;
    fill: currentColor;
    border-color: #78be20;
    background-color: #fff;
}
```
Avoid : 
```css
.mc-button--bordered {
    color: #78be20;
    fill: currentColor;
    border: 2px solid #78be20;
    background-color: #fff;
}
```
We have also duplicated/crushed property :
```
fill: currentColor;
```

We have also : 
`transition: all .2s ease;`

We don't need `all` setting, just target good rules for transition. (you can add some rules for your transition but `all` is not justify in this case and impact CPU)

We have also : 
`color: #fff;` by default.

Is it really useful by default ? It's squashed on some cases

- On wich browser the rseet property `margin:0;` is necessary ?
- We have 2 background properties, `background: none;` & `background-color: #78be20;` on default button.

## 🔬 Steps to reproduce the issue

Check the button properties in browser

## 📷 Screenshot (optional - it might be a gif)

![image](https://user-images.githubusercontent.com/3939846/77085637-e7d10180-6a00-11ea-8235-7a3a96b240c2.png)
